config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/",to:"home#index"
  resources :users
  resources :menus
  resources :orders
  resources :orderitems
  resources :cartitems
  get "/signin",to:"home#index",as: :new_session_page
  
  post "/signin",to:"sessions#signin",as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  post "/signup",to:"users#create",as: :signup
  get "/customers",to:"customers#index"
  get "/editmenus",to:"menus#change_menu",as: :update_menu
  get "/view_menus",to:"items#index",as: :view_items
  get "/bills",to:"bills#index",as: :bills
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ActiveRecord::Base
    validates :menu_name, presence:true, length: {maximum: 10}
    validates :menu_price, presence:true
end

app/models/order.rb
class Order < ActiveRecord::Base
    has_many :orderitems, dependent: :destroy
    belongs_to :user
end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
    belongs_to :order
    belongs_to :menu
    def top
        Orderitem.limit(2)
    end
end

app/models/user.rb
require 'bcrypt'
class User < ActiveRecord::Base
    has_secure_password
    has_many :orders
    has_many :orderitems, through: :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def ensure_user_role
    unless current_user.u_role=="owner"
      redirect_to view_items_path
    end
  end
  def current_user
    #memoization
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
    def index
        render "index"
    end
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
    def index
        render "index"
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def index
        render "customers/index"
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :ensure_user_logged_in
    def index
        render "index"
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        render "index"
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    def index
        render "index"
    end
    def create
        menu_name=params[:menu_name]
        menu_price=params[:menu_price]
        menu=Menu.new(
            menu_name:menu_name,
            menu_price:menu_price
            )
        if menu.save
            redirect_to menus_path 
        else
            #flash[:error]=menu.erros.full_messages.join(", ")
            flash[:error]="All fields are mandatory and menu size should not exceed more than 10!"
            redirect_to menus_path
        end
    end
    def change_menu
        render "change"
    end
    def update
        menu=Menu.find_by(menu_name:params[:menu_name])
        if menu
            menu.menu_price=params[:menu_price]
            menu.save!
            redirect_to edit_menus_path
        else
            flash[:error]="Invalid menu name"
            redirect_to update_menu
        end
    end

   
        



end

app/controllers/orderitems_controller.rb
class OrderitemsController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    
    def index
        render "index"
    end
    def create
        
        id=current_user.id
        new_order = Order.create!(user_id:id,order_date:params[:order_date])
        
        new_order_item = Orderitem.create!(order_id: new_order.id,
            menu_id: params[:menu_id],
            menu_name: params[:menu_name],
            menu_price: params[:menu_price]
            )
    end
    def update
        id=params[:id]
        order=Order.find(id)
        order.status=true
        order.save!
    end
    def destroy
        id=params[:id]
        order=Order.find(id)
        order.delete
        redirect_to orders_path
    end
end

app/controllers/sessions_controller.rb
class SessionsController  < ApplicationController
    skip_before_action :ensure_user_logged_in
    def new
        render "new"
    end
    def signin
        user=User.find_by(u_email: params[:email])
        if user && user.authenticate(params[:password])
            session[:current_user_id]=user.id
            if user.u_role=="owner"
                #redirect_to "/"
                redirect_to menus_path
            else
                redirect_to "/customers"
            end
        else
            flash[:error]= "Login invalid. Enter correct credentials"
            redirect_to "/"
        end
    end
    def destroy
        session[:current_user_id] = nil
        @current_user = nil
        redirect_to "/"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :ensure_user_logged_in
    def index
        render "new"
    end
    def create
        u_name=params[:name]
        u_email=params[:email]
        u_password=params[:password]
        user=User.create(u_name:u_name,u_email:u_email,password:u_password,u_role:"customer")
        if user.save
            session[:current_user_id]=user.id
            redirect_to "/"
        else
            #flash[:error]=user.errors.full_messages.join(", ")
            flash[:error]="All the fields are mandatory!"
            redirect_to new_user_path
        end
    end

   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bills/index.html.erb
<h1>Bill summary </h1>

<section class="s2">
<label class="ll1">
<table class="menu-heading">
  <tr>
    <th class="menu-title">Menu name</th>
    <th class="menu-title">Menu price</th>
  </tr>
    <% user=User.find(@current_user.id)%>
        <% user.orders.each do |o|%>
            <% o.orderitems.each do |oi|%>
                <tr>
                <td class="menu-title"><%= oi.menu_name %></td>
                <td class="menu-title"><%= oi.menu_price %></td>
                
            <%end%>
        <%end%>
                <tr>
</table>

<br>
<hr>
<h3 class="h3">Total  :  Rs.    <%=User.find(@current_user.id).orderitems.sum(:menu_price) %>

</h3>

app/views/cartitems/index.html.erb
<h1>My cart</h1>



<section class="s2">
<label class="ll1">
<table class="menu-heading">
  <tr>
    <th class="menu-title">Order id</th>
    <th class="menu-title">Menu name</th>
    <th class="menu-title">Menu price</th>
    <th class="menu-title">Status</th>
    
  </tr>
 
  
    <% user= User.find(@current_user.id)%>
    <% user.orderitems.each do |i| %>
    <tr>
    <td class="menu-title"> <%= i.order_id %> </td>
    <td class="menu-title"> <%= i.menu_name %> </td>
    <td class="menu-title"> <%= i.menu_price %> </td>
    <% if Order.find(i.order_id).status==true%> 
      <td class="menu-title"> Delivered </td>
    <% elsif Order.find(i.order_id).status==nil%>
      <td class="menu-title"> Pending </td>
    <% else%>
      <td class="menu-title"> Pending</td>
  
    <%end%>
    
 
    
    <%end%>
    </td>
    </tr>
  
  

  </table>
  <br><br>
  <%=link_to "Checkout",bills_path %>

app/views/customers/index.html.erb
<i> <p>Food for the body is not enough . There must be food for the soul . Order your food , eat better and feel better!! </p> </i>
<%= link_to "View menu" ,view_items_path %>

app/views/home/index.html.erb
<head>
    <title> Cafeteria app </title>
</head>

<body>
    <main class = "Home-main">
        <h1 class = "Home-title">Cafeteria App</h1>

        <section class = "UsersNew">
            <%= form_with(url: sessions_path, method: "post") do |form| %>
                <div class = "Form-section">
                    <p class = "FormInput-label">Email: </p>
                    <%= form.email_field :email, class: "Form-input" %>
                </div>

                <div class = "Form-section">
                    <p class = "FormInput-label">Password: </p>
                    <%= form.password_field :password, class: "Form-input" %>
                </div>

                <div class = "Form-section">
                    <%= form.submit "Sign-in", class: "Form-section-submit" %>
                </div>
                <div class = "Form-section-links">
                <%= link_to "New user? Sign-up!", new_user_path %>
                </div>

                
            <% end %>
        </section>
    </main>
</body>

app/views/items/index.html.erb
<section class="s2">
<label class="ll1">
<table class="menu-heading">
  <tr>
    <th class="menu-title">Menu name</th>
    <th class="menu-title">Menu price</th>
    <th class="menu-title">Add to cart</th>
  </tr>



<% Menu.all.each do |menu| %>
  <tr>
   
    <td class="menu-title" name="menu_name"> <%=menu.menu_name%> </td>
    <td class="menu-title" name="menu_price"> <%=menu.menu_price%> </td>
    <td class="menu-title"> 
    <%= button_to "Add",
    orders_path(
        order_date: Date.today,
        menu_id: menu.id,
        menu_name: menu.menu_name,
        menu_price: menu.menu_price),
    method: :post
    %>
    

  </tr>

<%end%>
</table>
</label>

<br>
<%= link_to "View cart",cartitems_path %>




</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeteriaApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <p class="UserHeader">
        Welcome <%= @current_user.u_name %>
        <%= link_to "Sign-out", destroy_session_path, method: "delete" %>
      </p>
    <% end %>

    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/menus/change.html.erb
<main class="m1">      
<article><h1 class="h1h">Update menu </h1>
<%=link_to "Home",menus_path %> 
<%= form_with(url: "/menus/menu_name", method: "put",class:"s1") do%>
    <input type="text" placeholder="Menu name" class="textfield1" name="menu_name">
    <input type="text" class="textfield2" placeholder="Menu price" name="menu_price">
    <input type="submit" value="Update" class="b1" placeholder="Update">
<%end%>
<section class="s2">
<label class="ll1">
<table class="menu-heading">
  <tr>
    <th class="menu-title">Menu name</th>
    <th class="menu-title">Menu price</th>
  </tr>

<% Menu.all.each do |menu| %>
  <tr>
  
    <td class="menu-title"> <%=menu.menu_name%> </td>
    <td class="menu-title"> <%=menu.menu_price%> </td>
  </tr>
<%end%>
</table>
</label>


</section>

app/views/menus/index.html.erb
<main class="m1">      
<article><h1 class="h1h">Menu List </h1>
<%=link_to "Edit menu",update_menu_path%> 
<%=link_to "View orders",orders_path , class: "link-to"%>

<%= form_with(url: menus_path, method: "post",class:"s1") do%>
    <input type="text" placeholder="Menu name" class="textfield1" name="menu_name">
    <input type="text" class="textfield2" placeholder="Menu price" name="menu_price">
    <input type="submit" value="Add" class="b1" placeholder="Add">
<%end%>


<section class="s2">
<label class="ll1">
<table class="menu-heading">
  <tr>
    <th class="menu-title">Menu name</th>
    <th class="menu-title">Menu price</th>
  </tr>

<% Menu.all.each do |menu| %>
  <tr>
  
    <td class="menu-title"> <%=menu.menu_name%> </td>
    <td class="menu-title"> <%=menu.menu_price%> </td>
  </tr>
<%end%>
</table>
</label>


</section>

app/views/orders/index.html.erb
<h1>Orders</h1>



<section class="s2">
<label class="ll1">
<table class="menu-heading">
  <tr>
    <th class="menu-title">User id</th>
    <th class="menu-title">Order id</th>
    <th class="menu-title">Order date</th>
    <th class="menu-title">Status</th>
    

  </tr>
 
  
    <% User.all.each do |u|%>
        <% u.orders.order(:order_date).each do |i| %>
        <tr>
        
        <td class="menu-title"> <%=u.id%> </td>
        <td class="menu-title"> <%= i.id %> </td>
        <td class="menu-title"> <%= i.order_date %> </td>
        <%= form_with(url: "/orders/#{i.id}",method:"put") do %>
        <td class="menu-title"> <input type="checkbox" class="c1" 
        <%= i.status ? "checked" : ""%>
        onclick="this.form.submit()">
        </td>
        <%end%>
        <%if i.status==true%>
        <%= form_with(url:"/orders/#{i.id}",method:"delete") do %>
          <td class="menu-title"> <input type="image" src="trash.png" class="delete">
          </td>
        <%end%>
        <%end%>
    <%end%>
    </td>
    </tr>
    <%end%>
     
  
  

  </table>

app/views/users/new.html.erb
<article class="UsersNew-main">
<p class="NewUsers-title">Welcome new user! Sign-up!</p>

<section class = "UsersNew">
    <%= form_with(url: signup_path, method: "post") do |form| %>
        <div class = "Signup-Form-section">
            <p class="Signup-FormInput-label">Name: </p>
            <%= form.text_field :name, class: "Form-input" %>
        </div>
        
        <div class = "Signup-Form-section">
            <p class="Signup-FormInput-label">Email: </p>
            <%= form.email_field :email, class: "Form-input" %>
        </div>

        <div class = "Signup-Form-section">
            <p class="Signup-FormInput-label">Password: </p>
            <%= form.password_field :password, class: "Form-input" %>
        </div>
        

        <div class = "Signup-Form-section-submit">
            <%= form.submit "Sign Up!", class: "Signup-Form-submit" %><br>
            <%= link_to "Home", "/" ,class: "Signup-Form-HomeLink"%>
        </div>
    <% end %>
</section>
</article>